# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ ];
  # show early boot messages
  boot.initrd.kernelModules = [ "vc4" "bcm2835_dma" "i2c_bcm2835" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool-rpi1/snap/root";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "rpool-rpi1/nosnap/nix";
    fsType = "zfs";
  };

  fileSystems."/var/lib/docker" = {
    device = "rpool-rpi1/nosnap/docker";
    fsType = "zfs";
  };

  swapDevices = [{
    device =
      "/dev/disk/by-id/usb-Apacer_A_S340_120GB_0123456789ABCDEF-0:0-part2";
  }];

  /* sd-card
     swapDevices = [{
       device = "/swapfile";
       size = 1024;
     }];
  */

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
