# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "rpool/root";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6D29-2988";
    fsType = "vfat";
  };

  # fileSystems."/var/lib/docker" = {
  #   device = "/dev/disk/by-uuid/a4f24755-a566-4508-852c-30ab5e474576";
  #   fsType = "ext4";
  # };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/b2fb8548-6032-497e-9960-9341ff1e10db"; }];

}
